version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-onfly
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-onfly
    environment:
      PMA_ARBITRARY: 1
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    ports:
      - "8080:80"
    depends_on:
      - mysql
